name 'blp-gemrc'
version '3.0.0'
maintainer 'Bloomberg Infrastructure Engineering'
maintainer_email 'chef@bloomberg.net'
license 'Apache-2.0'
description 'Configures gemrc configuration file for RubyGems.'
long_description 'Configures gemrc configuration file for RubyGems.'

issues_url 'https://github.com/bloomberg-cookbooks/gemrc/issues'
source_url 'https://github.com/bloomberg-cookbooks/gemrc'
chef_version '>= 12.5'

supports 'aix'
supports 'centos'
supports 'redhat'
supports 'solaris2'
supports 'ubuntu'
supports 'windows'

depends 'chef-sugar'
